gtc/src/gtc/urls.py
from django.conf.urls import patterns, include, url


from django.contrib import admin
from django.views.generic.base import TemplateView

admin.autodiscover()



#from tastypie.api import Api
#from GlobalTagCollector.api import AccountTypesResource, QueueResource, AccountsResource, TagsResource
from GlobalTagCollector.admin2 import gt_queues_list, gt_queue_create, gt_queue_clone, gt_queue_edit, gt_queue_entries, gt_queue_entry_status_change, gt_queue_entry_multiple_status_change, admin_dashboard, gt_settings
from GlobalTagCollector.views import gt_conf_export, new_request, list_view, details_view, json_account_types, json_accounts, json_tags, json_records, json_queues_for_record, login, admin2_logout, record_container_map, json_warnings_gt, gt_list, gt_info, rcd_list, tag_list, gt_compare

from django.contrib.staticfiles.urls import staticfiles_urlpatterns


#v1_api = Api(api_name='v1')
#v1_api.register(AccountTypesResource())
#v1_api.register(QueueResource())
#v1_api.register(AccountsResource())
#v1_api.register(TagsResource())
regular_urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gtc.views.home', name='home'),
    # url(r'^gtc/', include('gtc.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),


    url(r'^admin/', include(admin.site.urls)),
#    url(r'^api/', include(v1_api.urls)),
    url(r'^admin2/gt_queues', gt_queues_list, name="gt_queue_list"),
    url(r'^admin2/gt_queue_create', gt_queue_create, name="gt_queue_create"),
    url(r'^admin2/gt_queue_clone/(?P<queue_id>\d+)/$', gt_queue_clone, name="gt_queue_clone"),
    url(r'^admin2/gt_queue_edit/(?P<queue_id>\d+)/$', gt_queue_edit, name="gt_queue_edit"),
    url(r'^admin2/gt_queue_entries/(?P<queue_id>\d+)/$', gt_queue_entries, name="gt_queue_entries"),
    url(r'^admin2/gt_queue_entry_status_change/(?P<gt_queue_entry_id>\d+)/(?P<new_status>[ARPIO])/', gt_queue_entry_status_change, name="gt_queue_entry_status_change"),
    url(r'^admin2/gt_queue_entry_multiple_status_change/(?P<gt_queue_id>\d+)/(?P<new_status>[ARPIO])/', gt_queue_entry_multiple_status_change, name="gt_queue_entry_multiple_status_change"),
    url(r'^gt_conf_export/(?P<gt_queue_name>[a-zA-Z0-9_\-]+)$', gt_conf_export, name="gt_conf_export"),


    url(r'^new-request$', new_request, name="new_request"),
    url(r'^tag_list$', tag_list, name="tag_list"),
    url(r'^rcd_list$', rcd_list, name="rcd_list"),
    url(r'^gt_list$', gt_list, name='gt_list'),
    url(r'^gt_info/(?P<gt_name>[a-zA-Z0-9_\-]+)$', gt_info, name='gt_info'),
    url(r'^gt_compare$', gt_compare, name="gt_compare"),
    url(r'^list_view$', list_view, name="list_view"),
    url(r'^details_view/(?P<id>\d+)$', details_view, name="details_view"),
    url(r'^submit-tag-success/$',
        name="submit_record_success",
        view=TemplateView.as_view(template_name="GlobalTagCollector/submit-record-success.html"),
    ),


    url(r'^json/account_types/$', json_account_types,),
    url(r'^json/accounts/$',json_accounts,),
    url(r'^json/tags/$',json_tags,),
    url(r'^json/records/$',json_records,),
    url(r'^json/queues/$', json_queues_for_record,),
    url(r'^json/warnings_gt/$', json_warnings_gt),
    url(r'^accounts/login/', login,),
    url(r'^admin2/$', admin_dashboard, name="admin_dashboard"),
    url(r'^admin2/gt_settings/$', gt_settings, name="gt_settings"),
    url(r'^debug/record_container_map$', record_container_map, name='record_container_map'),

    url(r'^admin2/logout', admin2_logout, name="admin2_logout" ),



)
#regular_urlpatterns += staticfiles_urlpatterns()

urlpatterns = patterns('',

    (r'^gtc/', include(regular_urlpatterns)),
    (r'', include(staticfiles_urlpatterns()))
)

gtc/src/GlobalTagCollector/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import pre_save
from django.utils.translation import ugettext as _
from GlobalTagCollector.managers import ImportedGTByDate
import re


class ServiceData(models.Model):
    '''
    Abstract model, that each model should inherit if it takes data from services. It is used to store information
    about manual changes of service information (if data entry was added or ignored manually).
    '''

    class Meta:
        abstract = True

    entry_manual_added = models.BooleanField(default=False, help_text="Was this entry added manually?")
    entry_ignored = models.BooleanField(default=False, help_text="Was this entry ignored manually due to some problems?")
    entry_administrator = models.ForeignKey(User, related_name="%(app_label)s_%(class)s_administrator", null=True, blank=True, help_text="Administrator, who edited this entry")
    entry_comment = models.TextField(blank=True, help_text="Reson, why this entry was edited")
    entry_creation_date = models.DateTimeField(auto_now_add=True, help_text="When entry was inserted?")
    entry_editing_date = models.DateTimeField(auto_now=True, help_text="When entry was modified?")
    entry_ignoring_canceled = models.DateTimeField(null=True, blank=True, help_text="If was ignored, when ignoring was canceled.")


class AccountType(ServiceData):
    '''List of all known account types'''

    class Meta:
        ordering = ['visible_for_users', 'name', 'title']
    title = models.CharField(max_length=200, unique=True, blank=False)
    name = models.CharField(max_length=200, unique=True, blank=False)
    connection_string = models.CharField(max_length=200,  unique=True, blank=True, null=True)
    visible_for_users = models.BooleanField(default=False)
    use_in_gt_import  = models.BooleanField(default=True)

    def save(self, force_insert=False, force_update=False, using=None):
        if self.connection_string == "":
            self.connection_string = None
        return super(AccountType, self).save(force_insert, force_update, using)

    def clean(self):
        if (self.connection_string == "" or self.connection_string is None) and self.visible_for_users:
            raise ValidationError("Account can not be saved. It can be visible for users, when there is value of conn_string")

    def __unicode__(self):
        return self.title


    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "title__icontains", "connection_string__icontains",


class Account(ServiceData):
    """Defines model for managing accounts (of tags & records)"""

    class Meta:
        unique_together = (
            ("name", "account_type"),
        )

    name = models.CharField(max_length=200)
    account_type = models.ForeignKey(AccountType)
    use_in_gt_import  = models.BooleanField(default=True)
    #tags_list_hash is used to monitor if tags for account has changed in remote services
    tags_list_hash = models.CharField(max_length=40, blank=True, db_index=True, help_text="Storing hash tag list page")

    def __unicode__(self):
        return self.name

    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",

    def related_label(self):
        return u"%s - %s " % (self.name, self.account_type.title, ) #is it bug, becuase shows id?



class HardwareArchitecture(ServiceData):
    """List of architecures for which software is avaibable"""

    name = models.CharField(blank=False, max_length=200, unique=True, help_text=_("Name of hardware achitecture"))

    def __unicode__(self):
        return self.name

    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",


class SoftwareRelease(ServiceData):
    """CMSSW software relases"""

    class Meta:
        ordering = ['internal_version',]

    name = models.CharField(blank=False, max_length=200, unique=True, help_text=_("Name of CMS_SW release"))
    internal_version = models.IntegerField(unique=True, help_text=_("Helps to compare CMS_SW relase versions"))
    hardware_architecture = models.ManyToManyField(HardwareArchitecture)
    records_updated = models.BooleanField(default=False)

    def get_major_version(self):
        return self.internal_version / 100000000
    major_version = property(get_major_version)

    def __unicode__(self):
        return self.name

    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",


class ObjectForRecords(ServiceData):
    """Object and record mapping"""

    name = models.CharField(blank=False, max_length=200, unique=True,
                            help_text=_("Object related with a Tag (helps to get a record)"))
    parent_name = models.CharField(blank=True, max_length=200, unique=False,
        help_text=_("Object related with a Tag (helps to get a record)"))

    def __unicode__(self):
        return self.name


    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",

class Record(ServiceData):
    """Record of a tag"""

    class Meta:
        unique_together = (("object_r", "name",),)
        ordering = ['name', "object_r"]

    object_r = models.ForeignKey(ObjectForRecords)
    name = models.CharField(blank=False, max_length=200)
    software_release = models.ManyToManyField(SoftwareRelease)

    def tags(self):
        return Tag.objects.filter(object_r__id=self.object_r.id)

    def __unicode__(self):
        return self.name


    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",


class Tag(ServiceData):
    """Tag bellonging to the account"""
    #TODO add fields to tag model
#    #mayby should be moved to in separate table
#    #deleted = models.BooleanField(default=False)
#    #ready_for_deletion = models.BooleanField(default=False)

    class Meta:
        unique_together = (("account", "name", "object_r"),)

    name = models.CharField(blank=False, max_length=200, )
    account = models.ForeignKey(Account)
    object_r = models.ForeignKey('ObjectForRecords')

    def __unicode__(self):
        return self.name

    def records(self):
        return Record.objects.filter(object_r__id=self.object_r.id)

    def related_label(self):
        return u"%s (%s) < %s < %s" % (self.name, self.id, self.account.name, self.account.account_type.title)

    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",

class GlobalTagRecordValidationError(ValidationError):
    def __init__(self, tag, record):
        message = "Record does not belong to the tag. "
        message += "Tag id: {{tag_id}}, Tag name: {{tag_name}}."
        message += "Record id:{{record_id}}, Record name:{{record_name}}. "
        msg = message.format(tag_id=tag.id, tag_name=tag.name, record_id=record.id, record_name=record.name)
        super(GlobalTagRecordValidationError, self).__init__(msg)


class GlobalTag(ServiceData):
    """Global tag names"""

    class Meta:
           ordering = ('name',  )


    name = models.CharField(blank=False, max_length=100, unique=True, help_text=_("Name of a global tag"))
 #   created_externally = models.BooleanField(help_text=_("Is it found in external services? (Not created with admin)"))
    external_finding_timestamp = models.DateTimeField(null=True, help_text=_("When global tag was found in webservices"))
    internal_creation_timestamp = models.DateTimeField(null=True, help_text=_("When administrator created global tag"))
    creator = models.ForeignKey(User, null=True, help_text=_("Administrator who created Global Tag (if any)"))

    warnings = models.TextField(blank=True)
    errors = models.TextField(blank=True)

    has_warnings = models.BooleanField(default=True)
    has_errors = models.BooleanField(default=True)

    objects = models.Manager()
    imported = ImportedGTByDate()

    def __unicode__(self):
        return self.name



    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",

#    def add_active_records_from_queue(self, queue): #FIX transactional
#        for item in queue.active_items():
#            gtr = GTRecord(
#                    global_tag=self,
#                    tag=item.tag,
#                    record=item.record,
#                    label=item.label
#                    ).save()


class GlobalTagRecord(models.Model):
    """Records belonging to Global Tag"""

    class Meta:
    #        verbose_name = "GT Item"
        unique_together = (
        ("global_tag", "tag", "record", "label"),
        )

    global_tag = models.ForeignKey(GlobalTag)
    tag = models.ForeignKey(Tag)
    record = models.ForeignKey(Record)
    label = models.CharField(blank=True, max_length=200)
    pfn = models.CharField(blank=True, max_length=400)
    #TODO consistency check frontier_connection = models.CharField(blank=False, max_length=100) #Leave for consistency check

    def clean(self):
        if not (self.tag.object_r == self.record.object_r) or (self.tag.object_r.parent_name == self.record.object_r.name):
            #raise ValidationError('Record does not belong to the tag')
            raise GlobalTagRecordValidationError(self.tag, self.record)

    def __str__(self):
        return "GT:%s Tag:%s Container:%s Record:%s label:%s" % (self.global_tag.name, self.tag.name, self.tag.object_r.name, self.record.name, self.label)

#------------------------------------------------------------------------------

class GTAccount(models.Model):
    """Global tags has also an accounts. Here is list of them"""

    #    class Meta:
    #        verbose_name = "GT Account"

    name = models.CharField(blank=False, max_length=200, unique=True, help_text=_("Account of global tag"))

    def deletable(self):
        print self.gtqueue_set.count()

gtc/src/GlobalTagCollector/templates/admin2/dashboard.html
{% extends "app_layout.html" %}
{# load humanize #}


{% block title %}Global Tag Collector{% endblock %}

{% block media%}
{{ block.super }}
<style type="text/css">
.dashboard-container{
    border: #CCCCCC solid 1px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;box-sizing: border-box;
    border-radius: 3px 3px 0px 0px;
    -moz-border-radius: 3px 3px 0px 0px;
    -webkit-border-radius: 3px 3px 0px 0px;
}
.dashboard-container h3{
    background-color: #eef2f9;
    border-bottom: 1px solid #CCCCCC;
    margin-top: 0px;
}
#gt_queue_tbl {
    margin: 0 auto;
    width: 100%;
}
#gt_queue_tbl td {
    padding-left: 20px;
}
</style>

{% endblock %}

{%  block content %}
{# load tags #}


<div class="row">
    <div class="span6">
        <h1>Dashboard</h1>
    </div>
</div>
<div class="row">
    <div class="span6 dashboard-container" >
        <h3>Global Tags</h3>
        <table class="span6" style="margin-bottom: 10px;">
            <tr>
                <td>Global Tag Count</td>
                <td><span class="badge">{{ global_tag_count }}</span></td>
            </tr>
            <tr>
                <td>Not imported Global Tag count</td>
                <td>
                    {% if not_imported_global_tags|length == 0 %}
                        <span class="badge badge-success">
                    {% else %}
                       <span class="badge badge-important">
                    {% endif %}
                    {{ not_imported_global_tags|length }}
                    </span>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    {% if not_imported_global_tags %}
                        Not imported GT list:
                        <ul>
                        {% for not_imported_global_tag in not_imported_global_tags %}
                            <li><a href="{%url gt_info gt_name=not_imported_global_tag.name%}">{{not_imported_global_tag.name}}</a></li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Inconsistent Global Tag count</td>
                <td><span class="badge badge-important">{{ inconsistent_global_tags_count }}</span></td>
            </tr>
        </table>
    </div>

    <div class="span6 dashboard-container">
        <h3>Global Tags Queues</h3>
        <table class="span6" id="gt_queue_tbl">
            <tr>
                <td>GT queue count</td>
                <td><span class="badge">{{ global_tag_queue_count }}</span></td>
            </tr>
            <tr>
                <td>GT queue pending elements count</td>
                <td>
                    {% if global_tag_queue_pending_elements_count == 0 %}
                        <span class="badge badge-success">
                    {% else %}
                       <span class="badge badge-important">
                    {% endif %}
                        {{ global_tag_queue_pending_elements_count }}
                    </span>
                </td>
            </tr>
            <tr>
                <td colspan="2">

                    <table class="table table-striped table-condensed">
                        <caption style="text-align: left">Active Queues Statuses:</caption>
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Test status</th>
                        <th>Test time</th>
                        <th>Pending entries</th>
                    </tr>
                    </thead>
                    {% for open_queue in open_queues %}
                        <tr>
                            <td><a href="{% url gt_queue_entries queue_id=open_queue.id %}">{{ open_queue.name }}</a></td>
                            <td>N/A</td>
                            <td>N/A</td>
                            <td>{{open_queue.num_pending}}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="4">No data available</td>
                        </tr>
                    {% endfor %}
                    </table>
                </td>
            </tr>
        </table>
    </div>



</div>
{% endblock %}

gtc/src/GlobalTagCollector/templates/admin2/gt_queue_create.html
{% extends "app_layout.html" %}
{# load humanize #}


{% block title %}Global Tag Collector{% endblock %}

{% block media%}
{{ block.super }}
<style type="text/css">
    div #warn { color: black; }
    .table th:first-child { width: 25%; }
    div #gt_warning_box {
        margin: 0;
        padding: 3px 15px;
        float: right;
    }
    div #collapse_div {
        margin-top: 6px;
        width: 100%;
    }
</style>
<script type="text/javascript">
    $(document).ready(function() {
        // Hide error box by default
        $("#error_box").hide();

        // Last GT selector
        last_gt = $("select#id_last_gt");

        $("select#id_release_from").chosen();
        $("select#id_release_to").chosen();
        last_gt.chosen();

        last_gt.parent().append('<div id="gt_warning_box" class="alert alert-info"></div>');

        warn_box = $("#gt_warning_box");
        warn_box.html('<strong>WARNING: </strong>This GT has missing entries.');
        // Hide warnings box by default
        warn_box.hide();

        // Create collapsible div
        last_gt.parent().append('<div id="collapse_div"></div>');
        collapse_div = $("#collapse_div"); collapse_div.hide();
        
        last_gt.change(function(){
            $.get("/gtc/json/warnings_gt/?gt_id=" + $(this).val(), function(data){
                if (data.no_warnings) {
                    // Hide all warning elements
                    if (collapse_div.is(':visible')) collapse_div.slideUp(function(){ warn_box.hide(); });
                } else {
                    collapse_div.hide(); warn_box.show();
                    // Create and populate warnings info div
                    collapse_div.html('<div id="warn" class="alert alert-info"></div>');
                    for(var i=0; i<data.length; i++) {
                        $("#warn").append("Rcd: " + data[i].data.record + "<br />Tag: " + data[i].data.tag + "<br />PFN: " + data[i].data.pfn + "<br /><br />");
                    }
                    collapse_div.slideDown('slow');
                } // end else
            }, "json");
        }); // end change event

        // Validate queue name field
        $('#form_submit_new_queue').submit(function(e){
            var queue_name = $("#id_name").val();
            valid_regex = new RegExp('^[a-zA-Z0-9_]{1,100}$');

            if (!valid_regex.test(queue_name)) {
                $("#error_box").show();
                e.preventDefault();
            }
        }); // end submit event

    });
</script>
{% endblock %}

{%  block content %}
{# load tags #}


<div class="row">
    <div class="span5">
        <h1>Create GT queue</h1>
    </div>
    <div class="span7" style="float: right; margin-top: 12px;">
        <div id="error_box" class="alert alert-error" style="margin: 0;">
            <a onClick="$(this).parent().hide();">× </a>
            <strong>ERROR: </strong>Queue name can contain only characters, digits and underscores.
        </div>
    </div>
</div>

<form action="" id="form_submit_new_queue" method="POST">
    <div class="row">
        <div class="span12">
            {% csrf_token %}
            <table class="table table-condensed table-bordered">
            {% if queue_name %}
                <tr>
                    <th>Queue name</th>
                    <td>{{queue_name}}</td>
                </tr>
            {% endif %}
                {{gt_queue_form}}
            </table>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

gtc/src/GlobalTagCollector/templates/admin2/gt_queue_edit.html
{% extends "app_layout.html" %}
{# load humanize #}


{% block title %}Global Tag Collector{% endblock %}

{% block media%}
{{ block.super }}
<script type="text/javascript">
    $(document).ready(function() {
        // Hide error box by default
        $("#error_box").hide();

        $("select#id_release_from").chosen();
        $("select#id_release_to").chosen();
        $("select#id_last_gt").chosen();

        // Validate queue name field
        $('#form_edit_queue').submit(function(e){
            var queue_name = $("#id_name").val();
            valid_regex = new RegExp('^[a-zA-Z0-9_]{1,100}$');

            if (!valid_regex.test(queue_name)) {
                $("#error_box").show();
                e.preventDefault();
            }
        }); // end submit event
    });
</script>
{% endblock %}

{%  block content %}
{# load tags #}


<div class="row">
    <div class="span5">
        <h1>Edit GT Queue</h1>
    </div>
    <div class="span7" style="float: right; margin-top: 12px;">
        <div id="error_box" class="alert alert-error" style="margin: 0;">
            <a onClick="$(this).parent().hide();">× </a>
            <strong>ERROR: </strong>Queue name can contain only characters, digits and underscores.
        </div>
    </div>
</div>

<form action="{% url gt_queue_edit queue_id=gt_queue.id %}" id="form_edit_queue" method="POST">
    <div class="row">
        <div class="span12">
            {% csrf_token %}
            <table  class="table table-condensed table-bordered">
                <tr>
                    <th>Queue name</th>
                    <td>{{gt_queue.name}}</td>
                </tr>
                {{gt_queue_form}}
            </table>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

gtc/src/GlobalTagCollector/templates/admin2/gt_settings.html
{% extends "app_layout.html" %}
{# load humanize #}


{% block title %}Global Tag Collector :: Settings{% endblock %}

{% block media%}
{{ block.super }}
<style type="text/css">
    #id_name {
        width: 97%;
    }
    #id_entry_comment {
        width: 97%;
        max-width: 97%;
        height: 60px;
    }
</style>
<script>
    jQuery(document).ready(function(){

        // Hide error box by default
        $("#error_box").hide();

        // Request user focus by changing text opacity
        {% if not request.REQUEST.gt and form_submitted %}
            for(var i=0;i<3;i++) {
                $("tr:visible:last",".table-striped").fadeTo('fast', 0.4).fadeTo('fast', 1.0);
            } // end for
        {% else %}
            {% if not request.GET.del_hwa and not request.GET.del_acc and not request.GET.gt %}
                // FadeIn Animation on page load
                $("div.active").hide().fadeIn('normal');
            {% endif %}
        {% endif %}

        // Check for invalid put and show error message if so
        $('form').submit(function(e){
            input_field = $("#id_name").val()
            if ((input_field === null) || (input_field.trim().length < 2)){
                $("#error_box").show();
                e.preventDefault();
            } // end if
        });

        // GTC TAB
        jQuery(".chosen").chosen({ max_selected_options: 1 });

    });
</script>
{% endblock %}

{%  block content %}
{# load tags #}

<div class="row">
    <div class="span5">
        <h1>GTC Settings</h1>
    </div>
    <div class="span7" style="float: right; margin-top: 12px;">
        <div id="error_box" class="alert alert-error" style="margin: 0;">
            <a onClick="$(this).parent().hide();">× </a>
            <strong>ERROR: </strong>Please, check your input.
        </div>
    </div>
</div>

<div class="row">
    <div class="span12">
        <div class="tabbable">
            <ul class="nav nav-tabs">
                <li{% if not request.GET.section or request.GET.section == "hwa" %} class="active"{% endif %}><a href="?section=hwa">Hardware Architectures</a></li>
                <li{% if request.GET.section == "gtc" %} class="active"{% endif %}><a href="?section=gtc">GT Control</a></li>
                <li{% if request.GET.section == "acc" %} class="active"{% endif %}><a href="?section=acc">Account Control</a></li>
            </ul>
            <div class="tab-content">
                {% if not request.GET.section or request.GET.section == "hwa" %}
                <div class="tab-pane fade in active" id="hwa">
                    <form action="" id="form_hwa" method="POST">
                        <div class="row">
                            <div class="span4">
                                <table class="table table-striped table-condensed table-bordered">
                                    <tr>
                                        <th>Active Architectures</th>
                                        <th>Action</th>
                                        {% for a in hwa_objects_all %}
                                        <tr><td>{{a.name}}</td><td><a href="?section=hwa&del_hwa={{a.id}}"><i class="icon-trash"></i>Delete</a></td></tr>
                                        {% endfor %}
                                    </tr>
                                </table>
                            </div>
                            <div class="span8">
                                {% csrf_token %}
                                {{ hwa_form }}
                                <div class="form-actions" style="text-align: center;">
                                    <button type="submit" class="btn btn-success" id="button_add"><i class="icon-white icon-plus-sign"></i> Add Architecture</button>
                                    <a class="btn btn-danger" href="{% url gt_settings %}"><i class="icon-white icon-refresh"></i> Clean Form</a>
                                </div>
                            </div>
                        </div>
                    </form>
                    
                </div>
                {% endif %}
                {% if request.GET.section == "gtc" %}
                <div class="tab-pane fade in active" id="gtc">
                <form action="" id="gtc_form222" method="POST">
                {% csrf_token %}
                    <div class="row" style="min-height: 275px;">
                       <div class="span5">
                            <table class="table table-striped table-condensed table-bordered">
                                <tr>
                                    <th>Excluded GTs</th>
                                    <th>Action</th>
                                    {% for gt in gtc_objects_all %}
                                        {% if gt.entry_ignored %}
                                        <tr><td>{{ gt.name }}</td><td><a href="?section=gtc&gt={{gt.id}}"><i class="icon-check"></i> Recover</a></td></tr>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                            </table>
                        </div>
                        <div class="span4">
                            <select class="chosen" multiple="multiple" name="gt" id="id_name" data-placeholder="Click here to select a GT to exclude" style="width:300px;">
                            {% for gt in gtc_objects_all %}
                                {% if not gt.entry_ignored %}
                                <option value="{{ gt.id }}">{{ gt.name }}</option>
                                {% endif %}
                            {% endfor %}
                            </select>
                        </div>
                        <div class="span3">
                            <input type="hidden" name="exclude" value="1" />
                            <button id="submit_and_view" type="submit" class="btn btn-danger" style="width: 100%"><i class="icon-white icon-off"></i> Exclude GT</button>
                        </div>
                    </div>
                </form>
                </div>
                {% endif %}
                {% if request.GET.section == "acc" %}
                <div class="tab-pane fade in active" id="acc">
                    <form action="" id="form_acc" method="POST">
                        <div class="row">
                            <div class="span5">
                                <table class="table table-striped table-condensed table-bordered">
                                    <tr>
                                        <th>Manually Added Accounts</th>
                                        <th>Action</th>
                                        {% for a in acc_objects_all %}
                                        <tr><td>{{a.name}}</td><td><a href="?section=acc&del_acc={{a.id}}"><i class="icon-trash"></i>Delete</a></td></tr>
                                        {% endfor %}
                                    </tr>
                                </table>
                            </div>
                            <div class="span7">
                                {% csrf_token %}
                                {{ acc_form }}
                                <div class="form-actions" style="text-align: center;">
                                    <button type="submit" class="btn btn-success" id="button_add"><i class="icon-white icon-plus-sign"></i> Add Account</button>
                                    <a class="btn btn-danger" href="{% url gt_settings %}"><i class="icon-white icon-refresh"></i> Clean Form</a>
                                </div>
                            </div>
                        </div>
                    </form>
                    
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}