gtc/src/gtc/urls.py
from django.conf.urls import patterns, include, url


from django.contrib import admin
from django.views.generic.base import TemplateView

admin.autodiscover()



#from tastypie.api import Api
#from GlobalTagCollector.api import AccountTypesResource, QueueResource, AccountsResource, TagsResource
from GlobalTagCollector.admin2 import gt_queues_list, gt_queue_create, gt_queue_clone, gt_queue_edit, gt_queue_entries, gt_queue_entry_status_change, gt_queue_entry_multiple_status_change, admin_dashboard, gt_settings
from GlobalTagCollector.views import gt_conf_export, new_request, list_view, details_view, json_account_types, json_accounts, json_tags, json_records, json_queues_for_record, login, admin2_logout, record_container_map, json_warnings_gt, gt_list, gt_info, rcd_list, tag_list, gt_compare

from django.contrib.staticfiles.urls import staticfiles_urlpatterns


#v1_api = Api(api_name='v1')
#v1_api.register(AccountTypesResource())
#v1_api.register(QueueResource())
#v1_api.register(AccountsResource())
#v1_api.register(TagsResource())
regular_urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gtc.views.home', name='home'),
    # url(r'^gtc/', include('gtc.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),


    url(r'^admin/', include(admin.site.urls)),
#    url(r'^api/', include(v1_api.urls)),
    url(r'^admin2/gt_queues', gt_queues_list, name="gt_queue_list"),
    url(r'^admin2/gt_queue_create', gt_queue_create, name="gt_queue_create"),
    url(r'^admin2/gt_queue_clone/(?P<queue_id>\d+)/$', gt_queue_clone, name="gt_queue_clone"),
    url(r'^admin2/gt_queue_edit/(?P<queue_id>\d+)/$', gt_queue_edit, name="gt_queue_edit"),
    url(r'^admin2/gt_queue_entries/(?P<queue_id>\d+)/$', gt_queue_entries, name="gt_queue_entries"),
    url(r'^admin2/gt_queue_entry_status_change/(?P<gt_queue_entry_id>\d+)/(?P<new_status>[ARPIO])/', gt_queue_entry_status_change, name="gt_queue_entry_status_change"),
    url(r'^admin2/gt_queue_entry_multiple_status_change/(?P<gt_queue_id>\d+)/(?P<new_status>[ARPIO])/', gt_queue_entry_multiple_status_change, name="gt_queue_entry_multiple_status_change"),
    url(r'^gt_conf_export/(?P<gt_queue_name>[a-zA-Z0-9_\-]+)$', gt_conf_export, name="gt_conf_export"),


    url(r'^new-request$', new_request, name="new_request"),
    url(r'^tag_list$', tag_list, name="tag_list"),
    url(r'^rcd_list$', rcd_list, name="rcd_list"),
    url(r'^gt_list$', gt_list, name='gt_list'),
    url(r'^gt_info/(?P<gt_name>[a-zA-Z0-9_\-]+)$', gt_info, name='gt_info'),
    url(r'^gt_compare$', gt_compare, name="gt_compare"),
    url(r'^list_view$', list_view, name="list_view"),
    url(r'^details_view/(?P<id>\d+)$', details_view, name="details_view"),
    url(r'^submit-tag-success/$',
        name="submit_record_success",
        view=TemplateView.as_view(template_name="GlobalTagCollector/submit-record-success.html"),
    ),


    url(r'^json/account_types/$', json_account_types,),
    url(r'^json/accounts/$',json_accounts,),
    url(r'^json/tags/$',json_tags,),
    url(r'^json/records/$',json_records,),
    url(r'^json/queues/$', json_queues_for_record,),
    url(r'^json/warnings_gt/$', json_warnings_gt),
    url(r'^accounts/login/', login,),
    url(r'^admin2/$', admin_dashboard, name="admin_dashboard"),
    url(r'^admin2/gt_settings/$', gt_settings, name="gt_settings"),
    url(r'^debug/record_container_map$', record_container_map, name='record_container_map'),

    url(r'^admin2/logout', admin2_logout, name="admin2_logout" ),



)
#regular_urlpatterns += staticfiles_urlpatterns()

urlpatterns = patterns('',

    (r'^gtc/', include(regular_urlpatterns)),
    (r'', include(staticfiles_urlpatterns()))
)

gtc/src/GlobalTagCollector/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import pre_save
from django.utils.translation import ugettext as _
from GlobalTagCollector.managers import ImportedGTByDate
import re


class ServiceData(models.Model):
    '''
    Abstract model, that each model should inherit if it takes data from services. It is used to store information
    about manual changes of service information (if data entry was added or ignored manually).
    '''

    class Meta:
        abstract = True

    entry_manual_added = models.BooleanField(default=False, help_text="Was this entry added manually?")
    entry_ignored = models.BooleanField(default=False, help_text="Was this entry ignored manually due to some problems?")
    entry_administrator = models.ForeignKey(User, related_name="%(app_label)s_%(class)s_administrator", null=True, blank=True, help_text="Administrator, who edited this entry")
    entry_comment = models.TextField(blank=True, help_text="Reson, why this entry was edited")
    entry_creation_date = models.DateTimeField(auto_now_add=True, help_text="When entry was inserted?")
    entry_editing_date = models.DateTimeField(auto_now=True, help_text="When entry was modified?")
    entry_ignoring_canceled = models.DateTimeField(null=True, blank=True, help_text="If was ignored, when ignoring was canceled.")


class AccountType(ServiceData):
    '''List of all known account types'''

    class Meta:
        ordering = ['visible_for_users', 'name', 'title']
    title = models.CharField(max_length=200, unique=True, blank=False)
    name = models.CharField(max_length=200, unique=True, blank=False)
    connection_string = models.CharField(max_length=200,  unique=True, blank=True, null=True)
    visible_for_users = models.BooleanField(default=False)
    use_in_gt_import  = models.BooleanField(default=True)

    def save(self, force_insert=False, force_update=False, using=None):
        if self.connection_string == "":
            self.connection_string = None
        return super(AccountType, self).save(force_insert, force_update, using)

    def clean(self):
        if (self.connection_string == "" or self.connection_string is None) and self.visible_for_users:
            raise ValidationError("Account can not be saved. It can be visible for users, when there is value of conn_string")

    def __unicode__(self):
        return self.title


    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "title__icontains", "connection_string__icontains",


class Account(ServiceData):
    """Defines model for managing accounts (of tags & records)"""

    class Meta:
        unique_together = (
            ("name", "account_type"),
        )

    name = models.CharField(max_length=200)
    account_type = models.ForeignKey(AccountType)
    use_in_gt_import  = models.BooleanField(default=True)
    #tags_list_hash is used to monitor if tags for account has changed in remote services
    tags_list_hash = models.CharField(max_length=40, blank=True, db_index=True, help_text="Storing hash tag list page")

    def __unicode__(self):
        return self.name

    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",

    def related_label(self):
        return u"%s - %s " % (self.name, self.account_type.title, ) #is it bug, becuase shows id?



class HardwareArchitecture(ServiceData):
    """List of architecures for which software is avaibable"""

    name = models.CharField(blank=False, max_length=200, unique=True, help_text=_("Name of hardware achitecture"))

    def __unicode__(self):
        return self.name

    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",


class SoftwareRelease(ServiceData):
    """CMSSW software relases"""

    class Meta:
        ordering = ['internal_version',]

    name = models.CharField(blank=False, max_length=200, unique=True, help_text=_("Name of CMS_SW release"))
    internal_version = models.IntegerField(unique=True, help_text=_("Helps to compare CMS_SW relase versions"))
    hardware_architecture = models.ManyToManyField(HardwareArchitecture)
    records_updated = models.BooleanField(default=False)

    def get_major_version(self):
        return self.internal_version / 100000000
    major_version = property(get_major_version)

    def __unicode__(self):
        return self.name

    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",


class ObjectForRecords(ServiceData):
    """Object and record mapping"""

    name = models.CharField(blank=False, max_length=200, unique=True,
                            help_text=_("Object related with a Tag (helps to get a record)"))
    parent_name = models.CharField(blank=True, max_length=200, unique=False,
        help_text=_("Object related with a Tag (helps to get a record)"))

    def __unicode__(self):
        return self.name


    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",

class Record(ServiceData):
    """Record of a tag"""

    class Meta:
        unique_together = (("object_r", "name",),)
        ordering = ['name', "object_r"]

    object_r = models.ForeignKey(ObjectForRecords)
    name = models.CharField(blank=False, max_length=200)
    software_release = models.ManyToManyField(SoftwareRelease)

    def tags(self):
        return Tag.objects.filter(object_r__id=self.object_r.id)

    def __unicode__(self):
        return self.name


    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",


class Tag(ServiceData):
    """Tag bellonging to the account"""
    #TODO add fields to tag model
#    #mayby should be moved to in separate table
#    #deleted = models.BooleanField(default=False)
#    #ready_for_deletion = models.BooleanField(default=False)

    class Meta:
        unique_together = (("account", "name", "object_r"),)

    name = models.CharField(blank=False, max_length=200, )
    account = models.ForeignKey(Account)
    object_r = models.ForeignKey('ObjectForRecords')

    def __unicode__(self):
        return self.name

    def records(self):
        return Record.objects.filter(object_r__id=self.object_r.id)

    def related_label(self):
        return u"%s (%s) < %s < %s" % (self.name, self.id, self.account.name, self.account.account_type.title)

    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",

class GlobalTagRecordValidationError(ValidationError):
    def __init__(self, tag, record):
        message = "Record does not belong to the tag. "
        message += "Tag id: {{tag_id}}, Tag name: {{tag_name}}."
        message += "Record id:{{record_id}}, Record name:{{record_name}}. "
        msg = message.format(tag_id=tag.id, tag_name=tag.name, record_id=record.id, record_name=record.name)
        super(GlobalTagRecordValidationError, self).__init__(msg)


class GlobalTag(ServiceData):
    """Global tag names"""

    class Meta:
           ordering = ('name',  )


    name = models.CharField(blank=False, max_length=100, unique=True, help_text=_("Name of a global tag"))
 #   created_externally = models.BooleanField(help_text=_("Is it found in external services? (Not created with admin)"))
    external_finding_timestamp = models.DateTimeField(null=True, help_text=_("When global tag was found in webservices"))
    internal_creation_timestamp = models.DateTimeField(null=True, help_text=_("When administrator created global tag"))
    creator = models.ForeignKey(User, null=True, help_text=_("Administrator who created Global Tag (if any)"))

    warnings = models.TextField(blank=True)
    errors = models.TextField(blank=True)

    has_warnings = models.BooleanField(default=True)
    has_errors = models.BooleanField(default=True)

    objects = models.Manager()
    imported = ImportedGTByDate()

    def __unicode__(self):
        return self.name



    @staticmethod
    def autocomplete_search_fields():
        return "id__iexact", "name__icontains",

#    def add_active_records_from_queue(self, queue): #FIX transactional
#        for item in queue.active_items():
#            gtr = GTRecord(
#                    global_tag=self,
#                    tag=item.tag,
#                    record=item.record,
#                    label=item.label
#                    ).save()


class GlobalTagRecord(models.Model):
    """Records belonging to Global Tag"""

    class Meta:
    #        verbose_name = "GT Item"
        unique_together = (
        ("global_tag", "tag", "record", "label"),
        )

    global_tag = models.ForeignKey(GlobalTag)
    tag = models.ForeignKey(Tag)
    record = models.ForeignKey(Record)
    label = models.CharField(blank=True, max_length=200)
    pfn = models.CharField(blank=True, max_length=400)
    #TODO consistency check frontier_connection = models.CharField(blank=False, max_length=100) #Leave for consistency check

    def clean(self):
        if not (self.tag.object_r == self.record.object_r) or (self.tag.object_r.parent_name == self.record.object_r.name):
            #raise ValidationError('Record does not belong to the tag')
            raise GlobalTagRecordValidationError(self.tag, self.record)

    def __str__(self):
        return "GT:%s Tag:%s Container:%s Record:%s label:%s" % (self.global_tag.name, self.tag.name, self.tag.object_r.name, self.record.name, self.label)

#------------------------------------------------------------------------------

class GTAccount(models.Model):
    """Global tags has also an accounts. Here is list of them"""

    #    class Meta:
    #        verbose_name = "GT Account"

    name = models.CharField(blank=False, max_length=200, unique=True, help_text=_("Account of global tag"))

    def deletable(self):
        print self.gtqueue_set.count()

gtc/src/GlobalTagCollector/templates/app_layout.html
<!DOCTYPE HTML>
<html>


<head>

    {% block head %}
        <title>{% block title %}{% endblock %}</title>
    {%  endblock %}

    {#<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/app.css" />#}
    <style type="text/css">

        html, body {height: 100%;}

        #container {min-height: 100%;}

        #content {overflow:auto;
            margin-top: 40px; /*fix for menu*/
            padding-bottom: 90px;}  /* must be same height as the footer */

        #footer {position: relative;
            margin-top: -91px; /* negative value of footer height */
            height: 90px;
            clear:both;}

        /*Opera Fix*/
        body:before {
            content:"";
            height:100%;
            float:left;
            width:0;
            margin-top:-32767px;/
        }




  
</style>

<!--[if !IE 7]>
	<style type="text/css">
		#container {display:table;height:100%}
	</style>
<![endif]-->
    <script language="javascript" type="text/javascript" src="/libs/jquery-1.7.2.js"></script>
    <script language="javascript" type="text/javascript" src="/libs/chosen/0.9.8-2012.11.07/chosen/chosen.jquery.min.js"></script>
    <script language="javascript" type="text/javascript" src="/libs/bootstrap/2.1.0/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="/libs/bootstrap/2.1.0/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/libs/chosen/0.9.8-2012.11.07/chosen/chosen.css">
    <script type="text/javascript">
        $(document).ready(function() {
            $('.dropdown-toggle').dropdown();
        });

    </script>

    {% block media%}{% endblock %}

</head>


<body>
{% block body %}
    {% block header %}

        {%  block project_menu  %}{% include "blocks/project_menu.html" %}{% endblock %}
        {%  block application_menu  %}{% endblock %}
        {%  block application_title %}{% endblock %}
    {% endblock %}

    <div id="container" class="container">
            <div id="content" >
                {% block content %}dsffsdfdsfdsfds{% endblock %}
            </div>
    </div>

    {% block footer %}{% include "blocks/footer.html" %}{% endblock %}

{% endblock %}


</body>


</html>

gtc/src/GlobalTagCollector/templates/base.html
<!DOCTYPE HTML>
<html>
<head>
    {% block head %}
        <title>{% block title %}{% endblock %}</title>
    {%  endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

gtc/src/GlobalTagCollector/templates/details_view.html
{% extends "app_layout.html" %}

{% block title %}Global Tag Collector{% endblock %}

{% block media%}
    {{ block.super }}

{% endblock %}

{% block content %}
    <div class="row">
    <br />
<h2 class="span2">Details</h2>
<h5 style="color: #808080;">ID #{{ entry.id }}, Submitted {{ entry.submitting_time|date:"d/m/Y H:i" }}, Review: {% if entry.administration_time %}{{ entry.administration_time|date:"d/m/Y H:i" }}{% else %}No{% endif %}</h5>


    </div>

<table class="table table-striped table-condensed table-bordered">
    <tr>
        <th>Account type</th>
        <th>Account</th>
        <th>Tag</th>
        <th>Record</th>
        <th>Label</th>
    </tr>
    <tr>
        <td style="border-bottom: 0px;">{{ entry.tag.account.account_type }}</td>
        <td style="border-bottom: 0px;">{{ entry.tag.account }}</td>
        <td style="border-bottom: 0px;">{{ entry.tag }}</td>
        <td style="border-bottom: 0px;">{{ entry.record }}</td>
        <td style="border-bottom: 0px;">{{ entry.label }}</td>
    </tr>
    <tr>
        <th colspan="5"><br />Comment</th>
    </tr>
    <tr>
        <td colspan="5" style="border-bottom: 0px;">{{ entry.comment }}</td>
    </tr>
</table>





{% endblock %}

gtc/src/GlobalTagCollector/templates/gt_compare.html
{% extends "app_layout.html" %}
{# load humanize #}


{% block title %}Global Tag Collector :: GT Compare{% endblock %}

{% block media%}
{{ block.super }}
    <style type="text/css">
        #content {
            min-height: 270px;
        }
    </style>
    <script>
        jQuery(document).ready(function(){
            // Hide error box by default
            $("#error_box").hide();

            jQuery(".chosen").chosen({ max_selected_options: 2 });

            $('#acc_check').change(function(c){
                $('#compare_form').submit();
            });

            // Check if exactly 2 releases have been chosen, otherwise show error message
            $('#compare_form').submit(function(e){
                var selected_releases = $(".chosen").val()
                if ((selected_releases === null) || (selected_releases.length != 2)) {
                    $("#error_box").show();
                    e.preventDefault();
                } else {
                    if (window.location.search == "") {
                        var acc_ignored = $("<input>").attr("type", "hidden").attr("name", "acc_ignored").val(1);
                        $(this).append($(acc_ignored));
                    }
                    $("#error_box").hide();
                } // end else
            })
        });
    </script>
{% endblock %}

{%  block content %}
{# load tags #}

<div class="row">
    <div class="span6">
        <h1 id="toppage">GT Compare</h1>
    </div>
</div>

<form action="" id="compare_form" method="GET">
<div class="row">
    <div class="span4">
        <!-- multiple dropdown -->
        <select class="chosen" multiple="true" name="compare" data-placeholder="Click here to select 2 GTs to compare" style="width:315px;">
        {% for gt in all_gts %}
            <option value="{{ gt.name }}" {% if gt.name in gts_to_compare %}selected="selected"{% endif %}>{{ gt.name }}</option>
        {% endfor %}
        </select>
    </div>
    <div class="span3">
        <input id="submit_and_view" type="submit" class="btn btn-info" value="Compare GTs" style="margin-left: 12px;" />
        <a class="btn btn-danger" href="{% url gt_compare %}" style="margin-left: 12px;">Clean</a>
    </div>
    <div class="span5">
        <div id="error_box" class="alert alert-error" style="margin: 0px; margin-right: 16px; padding: 4px">
            <a onClick="$(this).parent().hide();">×</a>
             <strong>ERROR: </strong>Please select <strong>exactly two</strong> GTs to compare.
        </div>
    </div>
</div>

{% if gts_compared %}
<div class="row" style="margin-top: 10px; margin-bottom: 10px;">
    <div class="span8">
        <a href="#" data-toggle="collapse" data-target="#same_tags">Click to show/hide the list of same tags in both GTs</a>
    </div>
    <div class="span4" style="width: auto; float: right;">
<!--         <label class="checkbox-label"> -->
            <input type="checkbox" id="acc_check" name="acc_ignored" value="1" {% if request.GET.acc_ignored %}checked="checked"{% endif %} style="vertical-align: top; "> Ignore account
<!--         </label> -->
    </div>
</div>

<div class="row collapse out" id="same_tags">
    <div class="span12">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th colspan="2">{{ gts_compared.2.tags|length }} tags in both GTs</th>
            </tr>
            <tr><th>Tag</th><th>Account</th></tr>
            {% for tag in gts_compared.2.tags %}
            <tr><td>{{ tag.0.0 }}</td><td>{{ tag.0.1 }}</td></tr>
            {% empty %}
            <tr><td colspan="2">- - -</td></tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="row">
    <div class="span12">
    <table class="table table-striped table-condensed table-bordered">
        <tr>
            <th colspan="5">
                {{ gts_compared.0.tags|length }} Tags in <span class="badge badge-success">{{ gts_compared.0.gt }}</span>
                but NOT in <span class="badge badge-info">{{ gts_compared.1.gt }}</span>
            </th>
        </tr>
        <tr><th>Tag</th><th>Record</th><th>Label</th><th>Comment</th><th>Account</th></tr>
        {% for entry in gts_compared.0.tags %}
        <tr><td>{{ entry.0.0 }}</td><td>{{ entry.0.1 }}</td><td>{{ entry.0.2 }}</td><td>{{ entry.0.3 }}</td><td>{{ entry.0.4 }}</td></tr>
        {% empty %}
        <tr><td colspan="5">- - -</td></tr>
        {% endfor %}
    </table>

    <table class="table table-striped table-condensed table-bordered">
        <tr>
            <th colspan="5">
                {{ gts_compared.1.tags|length }} Tags in <span class="badge badge-info">{{ gts_compared.1.gt }}</span>
                but NOT in <span class="badge badge-success">{{ gts_compared.0.gt }}</span>
            </th>
        </tr>
        <tr><th>Tag</th><th>Record</th><th>Label</th><th>Comment</th><th>Account</th></tr>
        {% for entry in gts_compared.1.tags %}
        <tr><td>{{ entry.0.0 }}</td><td>{{ entry.0.1 }}</td><td>{{ entry.0.2 }}</td><td>{{ entry.0.3 }}</td><td>{{ entry.0.4 }}</td></tr>
        {% empty %}
        <tr><td colspan="5">- - -</td></tr>
        {% endfor %}
    </table>
    </div>
</div>
{% endif %}
</form>

{% endblock %}

gtc/src/GlobalTagCollector/templates/gt_info.html
{% extends "app_layout.html" %}
{# load humanize #}


{% block title %}Global Tag Collector{% endblock %}

{% block media%}
{{ block.super }}
<style type="text/css">
table.gt_summary th{
    text-align: right;
    padding-right: 10px;
}
</style>

{% endblock %}

{%  block content %}
{# load tags #}


<div class="row">
    <div class="span6">
        <h1>GT Info {{gt_obj.name}}</h1>
    </div>
</div>

<div class="row">
    <div class="span12">

        <div class="tabbable"> <!-- Only required for left/right tabs -->
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab1" data-toggle="tab">GT summary</a></li>
                <li><a href="#tab4" data-toggle="tab">GT Entries</a></li>
                <li><a href="#tab2" data-toggle="tab">Warnings</a></li>
                <li><a href="#tab3" data-toggle="tab">Errors</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab1">
                    <table class="gt_summary">
                        <tr>
                            <th>Name</th>
                            <td>{{gt_obj.name}}</td>
                        </tr>
                        <tr>
                            <th></th>
                            <td>{{gt_obj.external_finding_timestamp}}</td>
                        </tr>
                        <tr>
                            <th>Internal creation timestamp</th>
                            <td>{{gt_obj.internal_creation_timestamp}}</td>
                        </tr>
                        <tr>
                            <th>Creator</th>
                            <td>{{gt_obj.creator}}</td>
                        </tr>
                        <tr>
                            <th>Has warnings?</th>
                            <td>{{gt_obj.has_warnings}}</td>
                        </tr>
                        <tr>
                            <th>Has errors?</th>
                            <td>
                                {% if gt_obj.has_errors %}
                                    <span class="badge badge-important">
                                {% else %}
                                     <span class="badge badge-success">
                                {% endif %}
                                {{gt_obj.has_errors}}
                                </span>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="tab-pane" id="tab2">
                    <pre>{{gt_obj.warnings}}</pre>
                </div>
                <div class="tab-pane" id="tab3">
                    <pre>{{gt_obj.errors}}</pre>
                </div>
                <div class="tab-pane" id="tab4">
                    <table class="table  table-striped table-bordered table-condensed">


                        {% for gt_entry in gt_obj.globaltagrecord_set.select_related %}
                        {% ifchanged gt_entry.tag.account.account_type.title%}
                        <tr><td colspan="4">Account type: <strong>{{gt_entry.tag.account.account_type.title}}</strong></td></tr>

                        <tr>
                            <th>Account name</th>
                            <th>Tag</th>
                            <th>Record</th>
                            <th>Label</th>
                        </tr>
                        {% endifchanged %}

                        <tr>
                            <td>{{gt_entry.tag.account.name}}</td>
                            <td>{{gt_entry.tag.name}}</td>
                            <td>{{gt_entry.record.name}}</td>
                            <td>{{gt_entry.label}}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="5">No data</td>
                        </tr>
                        {% endfor %}
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

gtc/src/GlobalTagCollector/templates/gt_list.html
{% extends "app_layout.html" %}
{# load humanize #}


{% block title %}Global Tag Collector{% endblock %}

{% block media%}
{{ block.super }}
{% endblock %}

{%  block content %}
{# load tags #}


<div class="row">
    <div class="span6">
        <h1 id="toppage">Global Tags</h1>
    </div>

</div>
<div class="row">
    <div class="span12">

        <div>
            Starts with:
            {% for gt_obj in gt_obj_list %}

            {% ifchanged gt_obj.name|first %}

                <a href="#{{gt_obj.name|first}}">{{gt_obj.name|first}}</a> |

            {% endifchanged %}

            {% endfor %}

        </div>

        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th>Name</th>
                <th>Has warnings</th>
                <th>Has errors</th>
                <th>External Finding Timestamp</th>
                <th>Internal Creation Timestamp</th>
                <th>Creator</th>
            </tr>
            {% for gt_obj in gt_obj_list %}

            {% ifchanged gt_obj.name|first %}
            <tr>
                <th id="{{gt_obj.name|first}}" colspan="6">{{gt_obj.name|first}} <a href="#toppage">Up</a></th>
            </tr>
            {% endifchanged %}


            <tr>
                <td><a href="{% url gt_info gt_name=gt_obj.name %}">{{gt_obj.name}}</a></td>
                <td>
                    {% if gt_obj.has_warnings %}
                    <span class="label label">{{gt_obj.has_warnings}}</span>
                    {% else %}
                    <span class="label label-success">{{gt_obj.has_warnings}}</span>
                    {% endif %}
                </td>
                <td>
                    {% if gt_obj.has_errors == False %}
                    <span class="label label-important">{{gt_obj.has_errors}}</span>
                    {% else %}
                    <span class="label label-success">{{gt_obj.has_errors}}</span>
                    {% endif %}
                </td>
                <td>{{gt_obj.external_finding_timestamp}}</td>
                <td>{{gt_obj.internal_creation_timestamp}}</td>
                <td>{{gt_obj.creator}}</td>

            </tr>
            {% empty %}
            <tr>
                <td colspan="9">No data available</td>
            </tr>
            {% endfor %}
        </table>


    </div>
</div>
{% endblock %}